# Generated by Django 4.1.7 on 2024-02-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
